import type { Product } from "./types";

/**
 * Catálogo JA Store Perfumaria.
 * Dados fictícios porém realistas, baseados no posicionamento real da loja
 * (importados originais + árabes selecionados). Preços em BRL.
 *
 * Camada de dados isolada: no futuro basta trocar este array por
 * chamadas a uma API mantendo a mesma interface `Product`.
 */
export const products: Product[] = [
  // ————————————————————————— ÁRABES —————————————————————————
  {
    id: "p-asad",
    slug: "lattafa-asad",
    image: "/produtos/lattafa-asad.png",
    name: "Asad",
    brand: "Lattafa",
    origin: "arabe",
    gender: "masculino",
    family: "amadeirado",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "O árabe que virou fenômeno. Asad abre com um whisky ambarado e pimenta preta e evolui para um coração de tabaco e abacaxi, fechando em baunilha e âmbar cremoso. Doce na medida, viril e com uma projeção que atravessa o dia.",
    notes: {
      top: ["Whisky", "Pimenta-preta", "Bergamota"],
      heart: ["Abacaxi", "Tabaco", "Violeta"],
      base: ["Baunilha", "Âmbar", "Patchouli"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 189.9,
    compareAtPrice: 249.9,
    stock: 23,
    rating: 4.9,
    reviewCount: 214,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 5,
    accent: "#5A3A1E",
    accent2: "#C79A5B",
    bottle: "flacon",
  },
  {
    id: "p-yara",
    slug: "lattafa-yara",
    image: "/produtos/lattafa-yara.png",
    name: "Yara",
    brand: "Lattafa",
    origin: "arabe",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Cremoso, adocicado e viciante. Yara combina orquídea e heliotrópio a um fundo de baunilha e sândalo que gruda na pele e nas roupas. O queridinho absoluto de quem começa no mundo dos árabes.",
    notes: {
      top: ["Orquídea", "Tangerina", "Heliotrópio"],
      heart: ["Gardênia", "Flor de laranjeira"],
      base: ["Baunilha", "Sândalo", "Almíscar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 179.9,
    compareAtPrice: 229.9,
    stock: 31,
    rating: 4.9,
    reviewCount: 342,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 4,
    accent: "#8E2C6B",
    accent2: "#E7A9CF",
    bottle: "orb",
  },
  {
    id: "p-khamrah",
    slug: "lattafa-khamrah",
    image: "/produtos/lattafa-khamrah.png",
    name: "Khamrah",
    brand: "Lattafa",
    origin: "arabe",
    gender: "unissex",
    family: "gourmand",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Uma sobremesa árabe em forma de perfume. Canela, tâmara e noz-moscada envolvem um fundo de baunilha, benjoim e praliné. Aconchegante, especiado e perfeito para as noites mais frias.",
    notes: {
      top: ["Canela", "Noz-moscada", "Bergamota"],
      heart: ["Tâmara", "Praliné", "Flor de laranjeira"],
      base: ["Baunilha", "Tonka", "Benjoim"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 224.9,
    stock: 18,
    rating: 4.8,
    reviewCount: 176,
    bestSeller: true,
    isNew: false,
    longevity: 5,
    sillage: 5,
    accent: "#6B3A16",
    accent2: "#C98A3E",
    bottle: "tall",
  },
  {
    id: "p-badee-amethyst",
    slug: "lattafa-badee-al-oud-amethyst",
    image: "/produtos/lattafa-badee-al-oud-amethyst.png",
    name: "Bade'e Al Oud Amethyst",
    brand: "Lattafa",
    origin: "arabe",
    gender: "unissex",
    family: "amadeirado",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Frutado-amadeirado de assinatura contemporânea. Framboesa e açafrão sobre um oud aveludado e patchouli. Elegante, moderno e com uma fixação impressionante.",
    notes: {
      top: ["Framboesa", "Açafrão", "Bergamota"],
      heart: ["Oud", "Rosa", "Patchouli"],
      base: ["Âmbar", "Baunilha", "Almíscar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 209.9,
    stock: 14,
    rating: 4.8,
    reviewCount: 98,
    longevity: 5,
    sillage: 5,
    accent: "#4B2C63",
    accent2: "#9B7BC0",
    bottle: "cube",
  },
  {
    id: "p-cdn-intense",
    slug: "armaf-club-de-nuit-intense-man",
    image: "/produtos/armaf-club-de-nuit-intense-man.png",
    name: "Club de Nuit Intense Man",
    brand: "Armaf",
    origin: "arabe",
    gender: "masculino",
    family: "amadeirado",
    categorySlug: "arabes",
    subtitle: "Eau de Toilette 105ml",
    description:
      "O clássico custo-benefício que todo mundo reconhece. Abacaxi e limão explosivos na abertura, um coração floral e uma base amadeirada com âmbar cinza. Presença garantida em qualquer ocasião.",
    notes: {
      top: ["Abacaxi", "Limão", "Bergamota", "Groselha-preta"],
      heart: ["Bétula", "Jasmim", "Rosa"],
      base: ["Âmbar cinza", "Almíscar", "Baunilha", "Musgo de carvalho"],
    },
    sizeMl: 105,
    concentration: "EDT",
    price: 199.9,
    compareAtPrice: 259.9,
    stock: 27,
    rating: 4.9,
    reviewCount: 289,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 5,
    accent: "#1C2A2E",
    accent2: "#6E8A8F",
    bottle: "tall",
  },
  {
    id: "p-amber-oud-gold",
    slug: "al-haramain-amber-oud-gold-edition",
    image: "/produtos/al-haramain-amber-oud-gold-edition.png",
    name: "Amber Oud Gold Edition",
    brand: "Al Haramain",
    origin: "arabe",
    gender: "unissex",
    family: "ambar",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 60ml",
    description:
      "Luxuoso e viciante. Uma abertura frutada e cintilante sobre um coração ambarado e base de baunilha, oud e almíscar. Sofisticação árabe em um frasco dourado icônico.",
    notes: {
      top: ["Frutas cítricas", "Bergamota"],
      heart: ["Âmbar", "Especiarias"],
      base: ["Oud", "Baunilha", "Almíscar branco"],
    },
    sizeMl: 60,
    concentration: "EDP",
    price: 279.9,
    stock: 9,
    rating: 4.9,
    reviewCount: 134,
    longevity: 5,
    sillage: 4,
    accent: "#7A5A16",
    accent2: "#D9B24E",
    bottle: "flacon",
  },
  {
    id: "p-jean-lowe-immortal",
    slug: "maison-alhambra-jean-lowe-immortal",
    image: "/produtos/maison-alhambra-jean-lowe-immortal.png",
    name: "Jean Lowe Immortal",
    brand: "Maison Alhambra",
    origin: "arabe",
    gender: "masculino",
    family: "aromatico",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Fresco, verde e elegante para o dia a dia. Uma interpretação aromática e sofisticada com gengibre, sálvia e um fundo amadeirado limpo. Versátil e corporativo.",
    notes: {
      top: ["Gengibre", "Cardamomo", "Bergamota"],
      heart: ["Sálvia", "Lavanda", "Gerânio"],
      base: ["Vetiver", "Cedro", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 169.9,
    stock: 20,
    rating: 4.7,
    reviewCount: 76,
    isNew: true,
    longevity: 4,
    sillage: 4,
    accent: "#22323A",
    accent2: "#7FA0A6",
    bottle: "cube",
  },
  {
    id: "p-fakhar-black",
    slug: "lattafa-fakhar-black",
    image: "/produtos/lattafa-fakhar-black.png",
    name: "Fakhar Black",
    brand: "Lattafa",
    origin: "arabe",
    gender: "masculino",
    family: "fougere",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Um fougère aromático limpo e sedutor, muito comparado a clássicos de grife. Lavanda e maçã na abertura, coração floral e base de baunilha e fava tonka. Elegância acessível.",
    notes: {
      top: ["Lavanda", "Maçã", "Bergamota"],
      heart: ["Gerânio", "Cravo", "Cânfora"],
      base: ["Baunilha", "Tonka", "Musgo de carvalho"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 164.9,
    stock: 16,
    rating: 4.7,
    reviewCount: 91,
    longevity: 4,
    sillage: 4,
    accent: "#20242B",
    accent2: "#6D7684",
    bottle: "tall",
  },
  {
    id: "p-hawas",
    slug: "rasasi-hawas-for-him",
    image: "/produtos/rasasi-hawas-for-him.png",
    name: "Hawas For Him",
    brand: "Rasasi",
    origin: "arabe",
    gender: "masculino",
    family: "aquatico",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Fresco, aquático e absurdamente versátil. Maçã e bergamota cintilantes, um coração ambarado e uma base amadeirada com almíscar. O árabe favorito para o calor e para agradar geral.",
    notes: {
      top: ["Maçã", "Bergamota", "Groselha-preta"],
      heart: ["Âmbar cinza", "Flor de laranjeira"],
      base: ["Almíscar", "Cedro", "Fava tonka"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 219.9,
    stock: 22,
    rating: 4.8,
    reviewCount: 158,
    bestSeller: true,
    longevity: 4,
    sillage: 4,
    accent: "#153A47",
    accent2: "#5F9BB0",
    bottle: "flacon",
  },
  {
    id: "p-ana-abiyedh-rouge",
    slug: "lattafa-ana-abiyedh-rouge",
    image: "/produtos/lattafa-ana-abiyedh-rouge.png",
    name: "Ana Abiyedh Rouge",
    brand: "Lattafa",
    origin: "arabe",
    gender: "unissex",
    family: "citrico",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 60ml",
    description:
      "Cítrico-amadeirado limpo e sofisticado. Uma abertura brilhante de bergamota e neroli sobre um fundo de âmbar e almíscar. Discreto, elegante e altamente elogiável.",
    notes: {
      top: ["Bergamota", "Neroli", "Cardamomo"],
      heart: ["Íris", "Gerânio"],
      base: ["Âmbar", "Almíscar", "Cedro"],
    },
    sizeMl: 60,
    concentration: "EDP",
    price: 154.9,
    stock: 13,
    rating: 4.7,
    reviewCount: 64,
    longevity: 4,
    sillage: 3,
    accent: "#6E2233",
    accent2: "#C98598",
    bottle: "cube",
  },
  {
    id: "p-yara-moi",
    slug: "lattafa-yara-moi",
    image: "/produtos/lattafa-yara-moi.png",
    name: "Yara Moi",
    brand: "Lattafa",
    origin: "arabe",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "A irmã mais frutada da Yara. Manga, coco e frutas tropicais sobre um coração floral e base cremosa de baunilha e sândalo. Solar, doce e perfeito para o verão.",
    notes: {
      top: ["Manga", "Coco", "Frutas tropicais"],
      heart: ["Ylang-ylang", "Jasmim"],
      base: ["Baunilha", "Sândalo", "Almíscar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 189.9,
    stock: 17,
    rating: 4.8,
    reviewCount: 52,
    isNew: true,
    longevity: 4,
    sillage: 4,
    accent: "#B15A2E",
    accent2: "#F0B27A",
    bottle: "orb",
  },
  {
    id: "p-laventure",
    slug: "al-haramain-l-aventure",
    image: "/produtos/al-haramain-l-aventure.png",
    name: "L'Aventure",
    brand: "Al Haramain",
    origin: "arabe",
    gender: "masculino",
    family: "amadeirado",
    categorySlug: "arabes",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Sofisticado, amadeirado e cremoso. Especiarias e maçã abrem caminho para um coração de rosa e um fundo profundo de sândalo, âmbar e musgo. Uma alternativa marcante e elegante.",
    notes: {
      top: ["Maçã", "Canela", "Bergamota"],
      heart: ["Rosa", "Cardamomo", "Zimbro"],
      base: ["Sândalo", "Âmbar", "Musgo", "Tonka"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 234.9,
    stock: 11,
    rating: 4.8,
    reviewCount: 87,
    longevity: 5,
    sillage: 4,
    accent: "#2A2320",
    accent2: "#8A7458",
    bottle: "tall",
  },

  // ————————————————————— IMPORTADOS MASCULINOS —————————————————————
  {
    id: "p-sauvage-edp",
    slug: "dior-sauvage-eau-de-parfum",
    image: "/produtos/dior-sauvage-eau-de-parfum.png",
    name: "Sauvage Eau de Parfum",
    brand: "Dior",
    origin: "importado",
    gender: "masculino",
    family: "ambar",
    categorySlug: "masculinos",
    subtitle: "Eau de Parfum 100ml",
    description:
      "O importado masculino mais desejado do Brasil. Bergamota da Calábria radiante sobre uma base ambarada de baunilha e ambroxan. Poderoso, magnético e versátil — do trabalho à noite.",
    notes: {
      top: ["Bergamota da Calábria", "Pimenta-do-reino"],
      heart: ["Lavanda", "Noz-moscada", "Elemi"],
      base: ["Ambroxan", "Baunilha", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 699.9,
    compareAtPrice: 799.9,
    stock: 15,
    rating: 4.9,
    reviewCount: 421,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 4,
    accent: "#1B2A33",
    accent2: "#5C7A86",
    bottle: "flacon",
  },
  {
    id: "p-bleu-edp",
    slug: "bleu-de-chanel-eau-de-parfum",
    image: "/produtos/bleu-de-chanel-eau-de-parfum.png",
    name: "Bleu de Chanel Eau de Parfum",
    brand: "Chanel",
    origin: "importado",
    gender: "masculino",
    family: "amadeirado",
    categorySlug: "masculinos",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Elegância atemporal em estado puro. Cítricos frescos, um coração de gengibre e noz-moscada e uma base de sândalo e cedro. O amadeirado aromático que nunca sai de moda.",
    notes: {
      top: ["Limão", "Hortelã", "Toranja", "Pimenta-rosa"],
      heart: ["Gengibre", "Noz-moscada", "Jasmim"],
      base: ["Sândalo", "Cedro", "Incenso", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 789.9,
    stock: 12,
    rating: 4.9,
    reviewCount: 356,
    bestSeller: true,
    longevity: 5,
    sillage: 4,
    accent: "#14202B",
    accent2: "#4E6B80",
    bottle: "cube",
  },
  {
    id: "p-1million",
    slug: "paco-rabanne-1-million",
    image: "/produtos/paco-rabanne-1-million.png",
    name: "1 Million",
    brand: "Paco Rabanne",
    origin: "importado",
    gender: "masculino",
    family: "amadeirado",
    categorySlug: "masculinos",
    subtitle: "Eau de Toilette 100ml",
    description:
      "Ousado, doce e inconfundível. Toranja e canela cintilantes, um coração de rosa e couro e uma base de âmbar e patchouli. O lingote dourado que marcou uma geração.",
    notes: {
      top: ["Toranja", "Hortelã", "Tangerina"],
      heart: ["Canela", "Rosa", "Especiarias"],
      base: ["Couro", "Âmbar", "Patchouli"],
    },
    sizeMl: 100,
    concentration: "EDT",
    price: 549.9,
    compareAtPrice: 619.9,
    stock: 18,
    rating: 4.8,
    reviewCount: 244,
    longevity: 4,
    sillage: 4,
    accent: "#7A5A16",
    accent2: "#D9B24E",
    bottle: "cube",
  },
  {
    id: "p-le-male",
    slug: "jean-paul-gaultier-le-male",
    image: "/produtos/jean-paul-gaultier-le-male.png",
    name: "Le Male",
    brand: "Jean Paul Gaultier",
    origin: "importado",
    gender: "masculino",
    family: "fougere",
    categorySlug: "masculinos",
    subtitle: "Eau de Toilette 125ml",
    description:
      "Um clássico sedutor no icônico frasco em forma de torso. Lavanda e hortelã refrescantes sobre uma base cremosa de baunilha e fava tonka. Doce, quente e absolutamente cativante.",
    notes: {
      top: ["Hortelã", "Lavanda", "Bergamota", "Cardamomo"],
      heart: ["Canela", "Cominho", "Flor de laranjeira"],
      base: ["Baunilha", "Tonka", "Sândalo", "Âmbar"],
    },
    sizeMl: 125,
    concentration: "EDT",
    price: 579.9,
    stock: 14,
    rating: 4.8,
    reviewCount: 198,
    longevity: 4,
    sillage: 4,
    accent: "#2A3A55",
    accent2: "#8AA0C0",
    bottle: "orb",
  },
  {
    id: "p-eros",
    slug: "versace-eros",
    image: "/produtos/versace-eros.png",
    name: "Eros",
    brand: "Versace",
    origin: "importado",
    gender: "masculino",
    family: "aromatico",
    categorySlug: "masculinos",
    subtitle: "Eau de Toilette 100ml",
    description:
      "Sedução em tom azul e dourado. Hortelã e maçã verde vibrantes, um coração de fava tonka e gerânio e uma base de baunilha, cedro e musgo. Fresco e viciante.",
    notes: {
      top: ["Hortelã", "Maçã verde", "Limão"],
      heart: ["Fava tonka", "Gerânio", "Âmbar"],
      base: ["Baunilha", "Cedro", "Vetiver", "Musgo de carvalho"],
    },
    sizeMl: 100,
    concentration: "EDT",
    price: 489.9,
    compareAtPrice: 559.9,
    stock: 21,
    rating: 4.8,
    reviewCount: 176,
    longevity: 4,
    sillage: 4,
    accent: "#123A3A",
    accent2: "#4FA0A0",
    bottle: "tall",
  },
  {
    id: "p-most-wanted",
    slug: "azzaro-the-most-wanted",
    image: "/produtos/azzaro-the-most-wanted.png",
    name: "The Most Wanted",
    brand: "Azzaro",
    origin: "importado",
    gender: "masculino",
    family: "ambar",
    categorySlug: "masculinos",
    subtitle: "Eau de Parfum Intense 100ml",
    description:
      "Intenso, doce e magnético. Cardamomo e um acorde de licor abrem para uma base viciante de baunilha bourbon e madeiras tostadas. O queridinho dos lançamentos recentes.",
    notes: {
      top: ["Cardamomo", "Licor amadeirado"],
      heart: ["Toffee", "Especiarias"],
      base: ["Baunilha bourbon", "Madeiras tostadas", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 629.9,
    stock: 10,
    rating: 4.8,
    reviewCount: 88,
    isNew: true,
    longevity: 5,
    sillage: 5,
    accent: "#3A1F1A",
    accent2: "#9A6A4E",
    bottle: "flacon",
  },
  {
    id: "p-acqua-profumo",
    slug: "armani-acqua-di-gio-profumo",
    image: "/produtos/armani-acqua-di-gio-profumo.png",
    name: "Acqua di Giò Profumo",
    brand: "Giorgio Armani",
    origin: "importado",
    gender: "masculino",
    family: "aquatico",
    categorySlug: "masculinos",
    subtitle: "Parfum 75ml",
    description:
      "O aquático mais elegante já criado. Notas marinhas e bergamota sobre um coração de sálvia e uma base fumê de patchouli e incenso. Sofisticação em forma de brisa do mar.",
    notes: {
      top: ["Bergamota", "Notas marinhas"],
      heart: ["Sálvia", "Gerânio", "Rosa"],
      base: ["Patchouli", "Incenso", "Âmbar"],
    },
    sizeMl: 75,
    concentration: "Parfum",
    price: 729.9,
    stock: 8,
    rating: 4.9,
    reviewCount: 142,
    longevity: 5,
    sillage: 4,
    accent: "#1A2B33",
    accent2: "#5A8090",
    bottle: "cube",
  },

  // ————————————————————— IMPORTADOS FEMININOS —————————————————————
  {
    id: "p-libre",
    slug: "ysl-libre-eau-de-parfum",
    image: "/produtos/ysl-libre-eau-de-parfum.png",
    name: "Libre Eau de Parfum",
    brand: "Yves Saint Laurent",
    origin: "importado",
    gender: "feminino",
    family: "floral",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 90ml",
    description:
      "A tensão entre a frescura da lavanda e o calor da flor de laranjeira. Um floral aromático ousado com fundo de baunilha e almíscar. Liberdade engarrafada.",
    notes: {
      top: ["Lavanda", "Mandarina", "Groselha-preta"],
      heart: ["Lavanda", "Flor de laranjeira", "Jasmim"],
      base: ["Baunilha", "Fava tonka", "Almíscar", "Cedro"],
    },
    sizeMl: 90,
    concentration: "EDP",
    price: 719.9,
    compareAtPrice: 799.9,
    stock: 13,
    rating: 4.9,
    reviewCount: 231,
    bestSeller: true,
    longevity: 5,
    sillage: 4,
    accent: "#2A2540",
    accent2: "#8A7CC0",
    bottle: "tall",
  },
  {
    id: "p-good-girl",
    slug: "carolina-herrera-good-girl",
    image: "/produtos/carolina-herrera-good-girl.png",
    name: "Good Girl",
    brand: "Carolina Herrera",
    origin: "importado",
    gender: "feminino",
    family: "oriental",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 80ml",
    description:
      "No icônico frasco de salto alto, um jogo entre o bem e o mal. Jasmim luminoso e fava tonka encontram café e cacau escuros. Sensual, marcante e inesquecível.",
    notes: {
      top: ["Amêndoa", "Café", "Bergamota"],
      heart: ["Jasmim Sambac", "Tuberosa"],
      base: ["Fava tonka", "Cacau", "Baunilha", "Praliné"],
    },
    sizeMl: 80,
    concentration: "EDP",
    price: 689.9,
    stock: 16,
    rating: 4.9,
    reviewCount: 267,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 5,
    accent: "#1C2440",
    accent2: "#6E7CC0",
    bottle: "orb",
  },
  {
    id: "p-la-vie-est-belle",
    slug: "lancome-la-vie-est-belle",
    image: "/produtos/lancome-la-vie-est-belle.png",
    name: "La Vie Est Belle",
    brand: "Lancôme",
    origin: "importado",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Um sorriso em forma de perfume. Íris nobre, jasmim e flor de laranjeira sobre um fundo doce de praliné, baunilha e patchouli. Feminino, luminoso e reconfortante.",
    notes: {
      top: ["Groselha-preta", "Pera"],
      heart: ["Íris", "Jasmim", "Flor de laranjeira"],
      base: ["Praliné", "Baunilha", "Patchouli", "Fava tonka"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 749.9,
    stock: 11,
    rating: 4.8,
    reviewCount: 203,
    longevity: 4,
    sillage: 4,
    accent: "#5A2A45",
    accent2: "#C084A6",
    bottle: "flacon",
  },
  {
    id: "p-olympea",
    slug: "paco-rabanne-olympea",
    image: "/produtos/paco-rabanne-olympea.png",
    name: "Olympéa",
    brand: "Paco Rabanne",
    origin: "importado",
    gender: "feminino",
    family: "oriental",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 80ml",
    description:
      "Uma deusa moderna. Flor de sal e baunilha salgada criam um contraste viciante com jasmim e âmbar. Doce, sensual e com uma assinatura única.",
    notes: {
      top: ["Água de gengibre", "Flor de tangerina", "Verde aquático"],
      heart: ["Jasmim", "Flor de sal"],
      base: ["Baunilha", "Âmbar", "Sândalo", "Cashmeran"],
    },
    sizeMl: 80,
    concentration: "EDP",
    price: 599.9,
    compareAtPrice: 669.9,
    stock: 14,
    rating: 4.8,
    reviewCount: 158,
    longevity: 4,
    sillage: 4,
    accent: "#7A5A1E",
    accent2: "#D9BE72",
    bottle: "orb",
  },
  {
    id: "p-paradoxe",
    slug: "prada-paradoxe",
    image: "/produtos/prada-paradoxe.png",
    name: "Paradoxe",
    brand: "Prada",
    origin: "importado",
    gender: "feminino",
    family: "floral",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 90ml",
    description:
      "Um floral âmbar que se transforma na pele. Neroli e bergamota luminosos sobre um coração de jasmim e uma base quente de almíscar e âmbar. Contemporâneo e magnético.",
    notes: {
      top: ["Bergamota", "Neroli"],
      heart: ["Jasmim líquido"],
      base: ["Âmbar", "Almíscar"],
    },
    sizeMl: 90,
    concentration: "EDP",
    price: 699.9,
    stock: 9,
    rating: 4.7,
    reviewCount: 74,
    isNew: true,
    longevity: 4,
    sillage: 4,
    accent: "#4A3A2A",
    accent2: "#B89A6E",
    bottle: "cube",
  },
  {
    id: "p-si",
    slug: "armani-si",
    image: "/produtos/armani-si.png",
    name: "Sì",
    brand: "Giorgio Armani",
    origin: "importado",
    gender: "feminino",
    family: "floral",
    categorySlug: "femininos",
    subtitle: "Eau de Parfum 100ml",
    description:
      "Elegância moderna e feminina. Cassis suculento, um coração de rosa e freesia e uma base chipre de baunilha, patchouli e almíscar. Sofisticado e envolvente.",
    notes: {
      top: ["Cassis", "Néctar"],
      heart: ["Rosa", "Freesia"],
      base: ["Baunilha", "Patchouli", "Almíscar", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 739.9,
    stock: 10,
    rating: 4.8,
    reviewCount: 129,
    longevity: 4,
    sillage: 4,
    accent: "#4A1F2E",
    accent2: "#B0708A",
    bottle: "flacon",
  },

  // ————————————————————— UNISSEX & NICHO —————————————————————
  {
    id: "p-br540",
    slug: "mfk-baccarat-rouge-540",
    image: "/produtos/mfk-baccarat-rouge-540.png",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    origin: "importado",
    gender: "unissex",
    family: "ambar",
    categorySlug: "unissex",
    subtitle: "Eau de Parfum 70ml",
    description:
      "Uma lenda do nicho. Açafrão e jasmim etéreos, um coração de âmbar cinza e cedro e uma assinatura de baunilha adocicada. Luminoso, sofisticado e inconfundível — pele de luxo.",
    notes: {
      top: ["Açafrão", "Jasmim"],
      heart: ["Âmbar cinza", "Madeira de cedro"],
      base: ["Resina de abeto", "Almíscar"],
    },
    sizeMl: 70,
    concentration: "EDP",
    price: 1890.0,
    stock: 5,
    rating: 4.9,
    reviewCount: 96,
    featured: true,
    longevity: 5,
    sillage: 5,
    accent: "#6E1A22",
    accent2: "#D98A6E",
    bottle: "cube",
  },
  {
    id: "p-kayali-vanilla",
    slug: "kayali-vanilla-28",
    image: "/produtos/kayali-vanilla-28.png",
    name: "Vanilla | 28",
    brand: "Kayali",
    origin: "importado",
    gender: "unissex",
    family: "gourmand",
    categorySlug: "unissex",
    subtitle: "Eau de Parfum 100ml",
    description:
      "A baunilha dos sonhos. Baunilha bourbon cremosa envolta em flor de brown sugar, tonka e almíscar. Aconchegante, doce na medida e viciante — pele quente o dia inteiro.",
    notes: {
      top: ["Brown sugar", "Flor de laranjeira"],
      heart: ["Baunilha bourbon", "Jasmim"],
      base: ["Tonka", "Almíscar", "Âmbar"],
    },
    sizeMl: 100,
    concentration: "EDP",
    price: 769.9,
    stock: 7,
    rating: 4.8,
    reviewCount: 61,
    isNew: true,
    longevity: 4,
    sillage: 3,
    accent: "#5A3A2E",
    accent2: "#C99A7A",
    bottle: "tall",
  },

  // ————————————————————— KITS & PRESENTES —————————————————————
  {
    id: "p-kit-arabes-descoberta",
    slug: "kit-descoberta-arabes",
    image: "/produtos/kit-descoberta-arabes.png",
    name: "Kit Descoberta Árabes",
    brand: "JA Store",
    origin: "arabe",
    gender: "unissex",
    family: "amadeirado",
    categorySlug: "kits",
    subtitle: "5 decants de 10ml",
    description:
      "A porta de entrada perfeita para o mundo dos árabes. Cinco decants de 10ml selecionados pela equipe JA: Asad, Yara, Khamrah, Bade'e Al Oud Amethyst e Hawas. Ideal para descobrir a sua assinatura antes de investir no frasco cheio.",
    notes: {
      top: ["Seleção variada"],
      heart: ["5 fragrâncias campeãs"],
      base: ["Embalagem para presente"],
    },
    sizeMl: 50,
    concentration: "EDP",
    price: 199.9,
    compareAtPrice: 259.9,
    stock: 25,
    rating: 4.9,
    reviewCount: 112,
    bestSeller: true,
    featured: true,
    longevity: 5,
    sillage: 5,
    accent: "#6E1A2B",
    accent2: "#C7A878",
    bottle: "cube",
  },
  {
    id: "p-kit-ela",
    slug: "kit-presente-ela",
    image: "/produtos/kit-presente-ela.png",
    name: "Kit Presente — Ela",
    brand: "JA Store",
    origin: "arabe",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "kits",
    subtitle: "Yara 100ml + Body Splash 50ml",
    description:
      "O presente que arranca sorrisos. O best-seller Yara em tamanho cheio acompanhado do body splash da mesma linha, em uma caixa rígida com laço, cartão personalizado e papel de seda. Pronto para presentear.",
    notes: {
      top: ["Yara EDP 100ml"],
      heart: ["Body Splash Yara 50ml"],
      base: ["Caixa presente + cartão"],
    },
    sizeMl: 150,
    concentration: "EDP",
    price: 249.9,
    stock: 19,
    rating: 4.9,
    reviewCount: 58,
    isNew: true,
    longevity: 5,
    sillage: 4,
    accent: "#8E2C6B",
    accent2: "#E7A9CF",
    bottle: "orb",
  },

  // ————————————————————— CORPO & BANHO —————————————————————
  {
    id: "p-yara-body-splash",
    slug: "lattafa-yara-body-splash",
    image: "/produtos/lattafa-yara-body-splash.png",
    name: "Yara Body Splash",
    brand: "Lattafa",
    origin: "arabe",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "corpo",
    subtitle: "All Over Spray 150ml",
    description:
      "A fragrância Yara em versão bruma corporal, para borrifar generosamente após o banho. Perfeita para camadas (layering) com o perfume ou para os dias em que você quer um toque leve e cremoso.",
    notes: {
      top: ["Orquídea", "Tangerina"],
      heart: ["Gardênia", "Flor de laranjeira"],
      base: ["Baunilha", "Sândalo", "Almíscar"],
    },
    sizeMl: 150,
    concentration: "Body Mist",
    price: 89.9,
    stock: 34,
    rating: 4.7,
    reviewCount: 47,
    longevity: 2,
    sillage: 2,
    accent: "#8E2C6B",
    accent2: "#E7A9CF",
    bottle: "tall",
  },
  {
    id: "p-brazilian-crush-62",
    slug: "sol-de-janeiro-brazilian-crush-62",
    image: "/produtos/sol-de-janeiro-brazilian-crush-62.png",
    name: "Brazilian Crush Cheirosa 62",
    brand: "Sol de Janeiro",
    origin: "importado",
    gender: "feminino",
    family: "gourmand",
    categorySlug: "corpo",
    subtitle: "Perfume Mist 90ml",
    description:
      "A bruma queridinha do verão. Pistache e caramelo salgado sobre baunilha e sândalo cremosos. Doce, calorosa e absurdamente cheirosa — o cheiro de pele bronzeada e feliz.",
    notes: {
      top: ["Pistache", "Amêndoa"],
      heart: ["Flor de baunilha", "Caramelo salgado"],
      base: ["Sândalo", "Almíscar"],
    },
    sizeMl: 90,
    concentration: "Body Mist",
    price: 149.9,
    stock: 28,
    rating: 4.8,
    reviewCount: 83,
    isNew: true,
    longevity: 3,
    sillage: 3,
    accent: "#B15A2E",
    accent2: "#F0C27A",
    bottle: "flacon",
  },
];

// ————————————————————— Seletores / coleções —————————————————————

export const getProduct = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const getById = (id: string): Product | undefined =>
  products.find((p) => p.id === id);

export const featuredProducts = (): Product[] =>
  products.filter((p) => p.featured);

export const bestSellers = (): Product[] =>
  products.filter((p) => p.bestSeller);

export const newArrivals = (): Product[] => products.filter((p) => p.isNew);

export const byCategory = (slug: string): Product[] =>
  products.filter((p) => p.categorySlug === slug);

export const relatedProducts = (product: Product, limit = 4): Product[] =>
  products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.categorySlug === product.categorySlug ||
          p.family === product.family ||
          p.gender === product.gender),
    )
    .slice(0, limit);

export const allBrands = (): string[] =>
  Array.from(new Set(products.map((p) => p.brand))).sort();

/** Produto-símbolo de uma categoria: best-seller com foto, com fallbacks. */
export const representativeProduct = (
  categorySlug: string,
): Product | undefined => {
  const inCat = byCategory(categorySlug);
  return (
    inCat.find((p) => p.bestSeller && p.image) ??
    inCat.find((p) => p.featured && p.image) ??
    inCat.find((p) => p.image) ??
    inCat[0]
  );
};
